### ISSUE TITLE
Problems with taxo

### ISSUE THREAD

**Issue by AragonAmazon** [umr-amap/BIOMASS#27]
Hello:
I am having problems with taxo function. It is not working, presents this error message
<!DOCTYPE html> <html lang="en"                      (right here) ------^
Would you please help me.
Thanks!

**Comment by MaximeRM** [comment]
Hi AragonAmazon, 
The problem has been likely fixed a few days back by Guillaume (huge thanks to him), due to a change in the tnrs services link. Can you please try to load the github version again and check whether your problem is solved?:

install.packages("remotes")
remotes::install_github('umr-amap/BIOMASS')

**Comment by marvin-11** [comment]
Hi
I have a problem with the CorrectTaxo function
does not work and displays the following error =
 in FUN (X [[i]], ...):
 Not Found (HTTP 404). Failed to connect to tnrs service. Retry maybe later.

Can you help me?

**Comment by MaximeRM** [comment]
Hi Marvin,

can you please try to reload the package with 

remotes::install_github('umr-amap/BIOMASS')

And check again whether you get an error?  If yes, can you please give a reproducible example?

Best
